WCF-Insurance/WCF-Cashmere

package-lock.json
package.json
tsconfig.json

remove the references to the @wcf/* packages from package.json, in favor of tsconfig redirect paths

fix: fix paths in tsconfig.json

---

package-lock.json
projects/cashmere/src/lib/sass/_colors.scss

Changed the brand color to wcf-red

docs: changed color

---

package-lock.json
projects/cashmere-examples/src/lib/xanthos-file-upload-overview/xanthos-file-upload-overview-example.component.html
projects/cashmere-examples/src/lib/xanthos-file-upload-overview/xanthos-file-upload-overview-example.component.ts
projects/cashmere-examples/src/project-template/src/app/cashmere.module.ts
projects/cashmere/src/lib/xanthos-file-upload/index.ts
projects/cashmere/src/lib/xanthos-file-upload/xanthos-constants.ts
projects/cashmere/src/lib/xanthos-file-upload/xanthos-file-upload.component.html
projects/cashmere/src/lib/xanthos-file-upload/xanthos-file-upload.component.scss
projects/cashmere/src/lib/xanthos-file-upload/xanthos-file-upload.component.spec.ts
projects/cashmere/src/lib/xanthos-file-upload/xanthos-file-upload.component.ts
projects/cashmere/src/lib/xanthos-file-upload/xanthos-file-upload.module.ts
projects/cashmere/src/lib/xanthos-file-upload/xanthos-file-upload.ts
projects/cashmere/src/public_api.ts
src/app/core/document-items.service.ts
src/app/shared/cashmere.module.ts

feat(xanthos-file-input): add Xanthos file input

---

projects/cashmere-examples/src/lib/table-filter/table-filter-example.component.html
projects/cashmere-examples/src/lib/table-overview/table-overview-example.component.html
projects/cashmere-examples/src/lib/table-overview/table-overview-example.component.ts
projects/cashmere-examples/src/lib/table-sort/table-sort-example.component.html
projects/cashmere/src/lib/sass/tables.scss

feat: table styles

---

package-lock.json
projects/cashmere-examples/src/lib/sidenav-overview/sidenav-overview-example.component.html
projects/cashmere-examples/src/lib/sidenav-overview/sidenav-overview-example.component.scss
projects/cashmere/src/lib/sidenav/sidenav.component.scss

update styles to keep Sidenav pulled to the left and filling the entire panel top to bottom

fix(sidenav styles): update styles to keep Sidenav pulled to the left

---

projects/cashmere-examples/src/lib/typeahead-overview/typeahead-overview-example.component.html
projects/cashmere-examples/src/lib/typeahead-overview/typeahead-overview-example.component.scss
projects/cashmere-examples/src/lib/typeahead-overview/typeahead-overview-example.component.ts
projects/cashmere-examples/src/project-template/src/app/cashmere.module.ts
projects/cashmere/src/lib/typeahead/index.ts
projects/cashmere/src/lib/typeahead/typeahead-item/typeahead-item.component.html
projects/cashmere/src/lib/typeahead/typeahead-item/typeahead-item.component.scss
projects/cashmere/src/lib/typeahead/typeahead-item/typeahead-item.component.spec.ts
projects/cashmere/src/lib/typeahead/typeahead-item/typeahead-item.component.ts
projects/cashmere/src/lib/typeahead/typeahead.component.html
projects/cashmere/src/lib/typeahead/typeahead.component.scss
projects/cashmere/src/lib/typeahead/typeahead.component.spec.ts
projects/cashmere/src/lib/typeahead/typeahead.component.ts
projects/cashmere/src/lib/typeahead/typeahead.module.ts
projects/cashmere/src/public_api.ts
src/app/core/document-items.service.ts
src/app/shared/cashmere.module.ts

add new typeahead component that allows you to filter through the dropdown data and select an option

feat(typeahead component): add typeahead component

---

projects/cashmere-examples/src/lib/typeahead-overview/typeahead-overview-example.component.ts
projects/cashmere/src/lib/typeahead/typeahead.component.html
projects/cashmere/src/lib/typeahead/typeahead.component.ts

* close results panel when tab key is pressed
* close results panel when click outside of typeahead
* valueChange event only emitting once per keystroke

fix typeahead bugs

---

projects/cashmere/src/lib/model/policy/Policy.ts

feat: add waiverofsubrogationtype to the policy modal

---

projects/cashmere/src/lib/typeahead/typeahead.component.ts

emit new event when enter is hit without an option selected

feat(typeahead): emit new event

---

projects/cashmere-examples/src/lib/button-link/button-link-example.component.html
projects/cashmere/src/lib/button/button.component.scss
projects/cashmere/src/lib/date-range/date-range/date-range.directive.ts
projects/cashmere/src/lib/radio-button/radio-button.component.scss
projects/cashmere/src/lib/sass/button.scss
projects/cashmere/src/lib/sass/form-field.scss
projects/cashmere/src/lib/select/select.component.scss

make border on form controls consistent (darker), remove underline from daterange form fields

fix(styles): fix some issues with styles on form controls

---

projects/cashmere-examples/src/lib/form-field-overview/form-field-overview-example.component.scss
projects/cashmere/src/lib/checkbox/checkbox.component.html
projects/cashmere/src/lib/checkbox/checkbox.component.scss
projects/cashmere/src/lib/checkbox/checkbox.component.spec.ts
projects/cashmere/src/lib/checkbox/checkbox.component.ts
projects/cashmere/src/lib/form-field/hc-form-field.component.html
projects/cashmere/src/lib/form-field/hc-form-field.component.scss
projects/cashmere/src/lib/form-field/hc-form-field.component.ts
projects/cashmere/src/lib/input/input.directive.ts
projects/cashmere/src/lib/radio-button/radio-button.component.html
projects/cashmere/src/lib/radio-button/radio-button.component.scss
projects/cashmere/src/lib/radio-button/radio.ts
projects/cashmere/src/lib/sass/_colors.scss
projects/cashmere/src/lib/sass/_mixins.scss
projects/cashmere/src/lib/sass/button.scss
projects/cashmere/src/lib/sass/checkbox.scss
projects/cashmere/src/lib/sass/form-field.scss
projects/cashmere/src/lib/select/select.component.scss

Ensures normal focus behavior for form fields. Considers tabIndex, spacebar key for checkboxes,
arrow keys for radio buttons and select boxes, and clicking label for checkbox or radio buttons.

fix(form field focus): apply proper focus to form fields #72

---

projects/cashmere-examples/src/lib/datepicker-min-max/datepicker-min-max-example.component.html
projects/cashmere-examples/src/lib/datepicker-min-max/datepicker-min-max-example.component.scss
projects/cashmere-examples/src/lib/datepicker-min-max/datepicker-min-max-example.component.ts
src/app/core/document-items.service.ts

I needed to add an example in order to verify this fix so I figured I may as well leave it there as it might be useful for users.

docs(datepicker): add datepicker example with min and max dates

---

projects/cashmere-examples/src/lib/sidenav-overview/sidenav-overview-example.component.html
projects/cashmere-examples/src/lib/sidenav-overview/sidenav-overview-example.component.scss
projects/cashmere-examples/src/lib/sidenav-overview/sidenav-overview-example.component.ts
projects/cashmere-examples/src/lib/sidenav-overview/sidenav-overview-example.module.ts
projects/cashmere/src/lib/drawer/drawer.component.scss
projects/cashmere/src/lib/radio-button/radio.ts
projects/cashmere/src/lib/sidenav/sidenav.component.html
projects/cashmere/src/lib/sidenav/sidenav.component.scss
projects/cashmere/src/lib/sidenav/sidenav.component.ts
projects/cashmere/src/lib/sidenav/sidenav.module.ts
src/app/app-routes.module.ts
src/app/app.component.html
src/app/app.component.scss
src/app/app.component.ts
src/app/demos/sidenav-demo/sidenav-demo.component.html
src/app/demos/sidenav-demo/sidenav-demo.component.scss
src/app/demos/sidenav-demo/sidenav-demo.component.ts
src/app/demos/sidenav-demo/sidenav-demo.module.ts
src/styles.scss

desktop and mobile friendly sidenav. Also addresses what appears to be a bug with Radio buttons not appropriately emitting which radio button was checked.

#91 mobile friendly sidenav component

---

guides/styles/forms.md
projects/cashmere/src/lib/accordion/accordion.component.scss
projects/cashmere/src/lib/sass/_typography.scss
projects/cashmere/src/lib/typeahead/typeahead-item/typeahead-item.component.scss
projects/cashmere/src/lib/typeahead/typeahead.component.scss
src/app/components/component-viewer/component-examples/example-viewer/example-viewer.component.html
src/app/components/component-viewer/component-examples/example-viewer/example-viewer.component.scss
src/app/components/component-viewer/component-viewer.component.scss
src/app/components/component-viewer/shared/document-viewer/document-viewer.component.scss
src/app/home/home.component.scss
src/styles.scss

Fixed typeahead styling.
Also fixed a few issues with some recent styling changes to Cashmere as a whole.

fix(typeahead styling): WCASHMERE-30 Fixed typeahead styles

---

projects/cashmere/src/lib/radio-button/radio-button.component.scss

Fixed the font size and a border issue with disabled radio buttons

fix(radio buttons): WCASHMERE-25 radio button style fixes

---

projects/cashmere/src/lib/header/header.component.html
projects/cashmere/src/lib/header/header.component.ts
projects/cashmere/src/lib/sidenav/sidenav.component.html
projects/cashmere/src/lib/sidenav/sidenav.component.ts

fix(sidenav): fix hcpopdirective error with sidenav

---

projects/cashmere/src/lib/typeahead/typeahead.component.ts

Typeahead issues

---

projects/cashmere-examples/src/lib/ellipsis-overview/ellipsis-overview-example.component.html
projects/cashmere-examples/src/lib/highlight-overview/highlight-overview-example.component.html
projects/cashmere-examples/src/lib/highlight-overview/highlight-overview-example.component.scss
projects/cashmere-examples/src/lib/highlight-overview/highlight-overview-example.component.ts
projects/cashmere-examples/src/lib/phone-overview/phone-overview-example.component.html
projects/cashmere-examples/src/lib/phone-overview/phone-overview-example.component.ts
projects/cashmere-examples/src/lib/ssn-masked-overview/ssn-masked-overview-example.component.html
projects/cashmere-examples/src/lib/ssn-masked-overview/ssn-masked-overview-example.component.ts
projects/cashmere-examples/src/lib/ssn-overview/ssn-overview-example.component.html
projects/cashmere-examples/src/lib/ssn-overview/ssn-overview-example.component.ts
projects/cashmere-examples/src/lib/zipcode-overview/zipcode-overview-example.component.html
projects/cashmere-examples/src/lib/zipcode-overview/zipcode-overview-example.component.ts
projects/cashmere/src/lib/pipes/highlight-match-type.ts
projects/cashmere/src/lib/pipes/highlight.pipe.ts
projects/cashmere/src/lib/pipes/index.ts
src/app/core/document-items.service.ts

There were some bugs in the highlight pipe that needed fixing which led to this becoming a breaking change :( - it is still a very simple upgrade but an enum needs to be used now instead of magic strings when using the highlight pipe.

fix highlight pipe and document existing pipes

---

projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.html
projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.scss
projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.ts
src/app/demos/sidenav-demo/sidenav-demo.component.html

stopped propogation on nested links and fixed the styling of the links when clicked

fix(sidenav): WCASHMERE-168: Fixed links and active highlight

---

projects/cashmere-examples/src/lib/modal-overview/modal-overview-example.component.html
projects/cashmere-examples/src/lib/modal-overview/modal-overview-example.component.scss
projects/cashmere-examples/src/lib/modal-overview/modal-overview-example.component.ts
projects/cashmere-examples/src/lib/modal-overview/modal-overview-example.module.ts
projects/cashmere/src/lib/modal/modal-window.component.scss
projects/cashmere/src/lib/modal/modal.md
projects/cashmere/src/lib/modal/modal.spec.ts
projects/cashmere/src/lib/sass/_modals.scss
projects/cashmere/src/lib/sass/modal.scss
src/app/core/document-items.service.ts

changes touching responsiveness, layout, examples, and forms

feat(136 modal component updates): update modal component

---

projects/cashmere-examples/src/lib/date-range/date-range-example.component.ts
projects/cashmere/src/lib/date-range/date-range.md

Added a description to the usage for the Date Range component that explains how to customize the
title text above the date inputs.

feat(date range): WCASHMERE-169: Usage info for changing titles

---

projects/cashmere/src/lib/header/header.component.html
projects/cashmere/src/lib/sidenav/sidenav.component.html

fix(sidenav/header): add icons to the profile menu

---

projects/cashmere-examples/src/lib/typeahead-title-multiple/typeahead-title-multiple-example.component.html
projects/cashmere-examples/src/lib/typeahead-title-multiple/typeahead-title-multiple-example.component.ts
projects/cashmere-examples/src/lib/typeahead-title/typeahead-title-example.component.html
projects/cashmere-examples/src/lib/typeahead-title/typeahead-title-example.component.ts
projects/cashmere/src/lib/typeahead-title/typeahead-title.component.html
projects/cashmere/src/lib/typeahead-title/typeahead-title.component.scss
projects/cashmere/src/lib/typeahead-title/typeahead-title.component.ts
projects/cashmere/src/lib/typeahead/typeahead.component.html
projects/cashmere/src/lib/typeahead/typeahead.component.scss
projects/cashmere/src/lib/typeahead/typeahead.component.ts
src/app/core/document-items.service.ts
tsconfig.json

Also added a few styling changes to the typeahead title

feat(typeahead): WCASHMERE-152: results pop up on focus

---

projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.html
projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.ts
projects/cashmere/src/lib/sidenav/sidenav.component.ts
src/app/demos/sidenav-demo/sidenav-demo.component.html
src/app/demos/sidenav-demo/sidenav-demo.component.ts

When a 3rd level link is the active link and its parents were dynamically added then it would not be
expanded to reveal the active link.

fix(sidenav): fix sidenav auto-expanding bug

---

projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.ts
src/app/app-routes.module.ts

add a null check to prevent an error from occuring and displaying in the console

fix(sidenav): prevent console error

---

projects/cashmere-examples/src/lib/input-phone-number/input-phone-number-example.component.html
projects/cashmere-examples/src/lib/input-phone-number/input-phone-number-example.component.ts
projects/cashmere/src/lib/input/phone-mask.directive.ts
projects/cashmere/src/lib/pipes/phone.pipe.ts

Validation of phone number format is now baked in so that the consumer doesn't need to provide it.
The phone number format now supports and auto-formats extensions. Also, updated the phone pipe to support phone number extensions.

fix(phone input): improve validation and formatting

---

projects/cashmere-examples/src/lib/radio-button-disabled/radio-button-disabled-example.component.html
projects/cashmere-examples/src/lib/radio-button-disabled/radio-button-disabled-example.component.ts
projects/cashmere/src/lib/radio-button/radio-button.component.scss
projects/cashmere/src/lib/radio-button/radio.ts

disabling a reactive from will now correctly disable all of the radio buttons and the selected radio
button will not look identical to the non-selected ones.

fix(radio button): disabling now works correctly - reactive forms

---

projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.html
projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.ts

Reverts WCF-Insurance/WCF-Cashmere#247
It actually made the issue worse 👎

Revert "fix(sidenav): fix active state of links"

---

projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.html
projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.scss
projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.ts
projects/cashmere/src/lib/sidenav/sidenav.component.ts

Not the actual solution to the problem but still a worthwhile fix that is kind of related (that might be a stretch).

fix(sidenav): fix toggling sidenav link children visible

---

projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts

When clicking up or down arrows, the numbers now wrap properly. The minutes now properly allow 00 as
the lowest value.

fix(time picker): WCASHMERE-191: Fixed time picker issues

---

projects/cashmere/src/lib/sass/input.scss

Just changed the input placeholder color to gray-30

fix(placeholder color): fix the color of the placeholder

---

projects/cashmere/src/lib/datepicker/datepicker-input/datepicker-input.directive.ts
projects/cashmere/src/lib/datepicker/datepicker.component.spec.ts
projects/cashmere/src/lib/datepicker/datetime/native-date-formats.ts

Date is formatted now to MM/DD/YYYY and now allows for entry of MMDDYYYY to be formatted
automatically on blur of input.

feat(datepicker): WCASHMERE-194: datepicker formatting

---

projects/cashmere/package.json

add sugar as a peer dependency to fix errors when building an application who has cashmere as a
dependency

fix(dependencies): fix sugar dependency

---

projects/cashmere-examples/src/lib/date-range-duration-constricted/date-range-duration-constricted-example.component.html
projects/cashmere-examples/src/lib/date-range-duration-constricted/date-range-duration-constricted-example.component.scss
projects/cashmere-examples/src/lib/date-range-duration-constricted/date-range-duration-constricted-example.component.ts
projects/cashmere/src/lib/date-range/date-range.md
projects/cashmere/src/lib/date-range/index.ts
projects/cashmere/src/lib/date-range/model/model.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts
src/app/core/document-items.service.ts

configure max range length for user

feat(date range): configure max range length

---

projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.html
projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.scss
src/app/demos/sidenav-demo/sidenav-demo.component.html

Text now wraps instead of using ellipses. Fixed an issue where text was overlapping icons. All
elements in a link align themselves to the middle of vertical.

feat(sidenav): WCASHMERE-202: Improved clarity of links

---

projects/cashmere-examples/src/lib/checkbox-indeterminate/checkbox-indeterminate-example.component.html
projects/cashmere-examples/src/lib/checkbox-indeterminate/checkbox-indeterminate-example.component.scss
projects/cashmere/src/lib/sass/checkbox.scss
src/app/core/document-items.service.ts

fixed indeterminate styling, added example, fixed label styling

feat(checkbox): wCASHMERE-46: styled checkbox and added to examples

---

projects/cashmere-examples/src/lib/input-currency/input-currency-example.component.html
projects/cashmere-examples/src/lib/input-currency/input-currency-example.component.ts
projects/cashmere-examples/src/lib/multi-select-picker-basic-text/multi-select-picker-basic-text-example.component.html
projects/cashmere-examples/src/lib/multi-select-picker-basic-text/multi-select-picker-basic-text-example.component.scss
projects/cashmere-examples/src/lib/multi-select-picker-focus/multi-select-picker-focus-example.component.html
projects/cashmere-examples/src/lib/multi-select-picker-form-disabled/multi-select-picker-form-disabled-example.component.html
projects/cashmere-examples/src/lib/multi-select-picker-form-disabled/multi-select-picker-form-disabled-example.component.scss
projects/cashmere-examples/src/lib/multi-select-picker-form/multi-select-picker-form-example.component.html
projects/cashmere-examples/src/lib/multi-select-picker-form/multi-select-picker-form-example.component.scss
projects/cashmere-examples/src/lib/multi-select-picker-rich-component/multi-select-picker-rich-component-example.component.html
projects/cashmere-examples/src/lib/multi-select-picker-rich-component/multi-select-picker-rich-component-example.component.scss
projects/cashmere-examples/src/lib/multi-select-picker-rich-template/multi-select-picker-rich-template-example.component.html
projects/cashmere-examples/src/lib/multi-select-picker-rich-template/multi-select-picker-rich-template-example.component.scss
projects/cashmere/src/lib/input/currency.directive.ts
projects/cashmere/src/lib/multi-select-picker/multi-select-picker.component.scss
projects/cashmere/src/lib/sass/checkbox.scss

I rushed the fix last time and didn't account for an initial value that is a number. I also snuck in a text color change for disabled checkboxes (per Tommy).

fix(currency input): fix currency input when value is a number

---

projects/cashmere-examples/src/lib/date-range-duration-constricted/date-range-duration-constricted-example.component.ts
projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.html
projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.scss
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts

Improve the way that the daterange component works when it is configured to function as a period
duration.

fix(daterange): improve duration functionality

---

projects/cashmere/src/lib/file-input/file-input.component.ts

fix(file input): clear out form value when X is clicked on uploaded file

---

projects/cashmere-examples/src/lib/file-input-custom-label-and-color/file-input-custom-label-and-color-example.component.html
projects/cashmere-examples/src/lib/file-input-custom-label-and-color/file-input-custom-label-and-color-example.component.ts
projects/cashmere-examples/src/lib/file-input-file-size-validation/file-input-file-size-validation-example.component.html
projects/cashmere-examples/src/lib/file-input-file-size-validation/file-input-file-size-validation-example.component.ts
projects/cashmere-examples/src/lib/file-input-file-type-validation/file-input-file-type-validation-example.component.html
projects/cashmere-examples/src/lib/file-input-file-type-validation/file-input-file-type-validation-example.component.ts
projects/cashmere-examples/src/lib/file-input-files-total-size-validation/file-input-files-total-size-validation-example.component.html
projects/cashmere-examples/src/lib/file-input-files-total-size-validation/file-input-files-total-size-validation-example.component.ts
projects/cashmere-examples/src/lib/file-input-overview/file-input-overview-example.component.ts
projects/cashmere/src/lib/file-input/file-input.component.html
projects/cashmere/src/lib/file-input/file-input.component.scss
projects/cashmere/src/lib/file-input/file-input.component.ts
projects/cashmere/src/lib/file-input/file-upload.ts
projects/cashmere/src/lib/file-input/index.ts
projects/cashmere/src/lib/file-input/validators/file-size.validator.ts
projects/cashmere/src/lib/file-input/validators/file-type.validator.spec.ts
projects/cashmere/src/lib/file-input/validators/file-type.validator.ts
projects/cashmere/src/lib/file-input/validators/files-total-size.validator.spec.ts
projects/cashmere/src/lib/file-input/validators/files-total-size.validator.ts
src/app/core/document-items.service.ts

You can now upload multiple files at a time with the file input component. Styles have been cleaned
up. Additional validators have been added.

feat(file input): enhance the file input to accept multiple files
