projects/cashmere-examples/src/lib/progress-bar/progress-bar-example.component.ts
projects/cashmere/src/lib/progress-bar/index.ts
projects/cashmere/src/lib/progress-bar/progress-bar.component.html
projects/cashmere/src/lib/progress-bar/progress-bar.component.scss
projects/cashmere/src/lib/progress-bar/progress-bar.component.spec.ts
projects/cashmere/src/lib/progress-bar/progress-bar.component.ts
projects/cashmere/src/lib/progress-bar/progress-item-status.ts

BREAKING CHANGE: progress items now use an enum for status

fix(progressbar): change focusing and completing functionality

---

projects/cashmere-examples/src/lib/input-suffix/input-suffix-example.component.html
projects/cashmere/src/lib/sass/_mixins.scss
projects/cashmere/src/lib/sass/form-field.scss

- Swapped input suffix icons to the user icon. 
- Adjusted labels to be aligned with field text. 
- Adjusted form field text to be properly aligned. 
- All input borders are gray-50. 
- Removed a transition animation that had been placed on the input suffix

fix: wcashmere23 input example update

---

projects/cashmere/src/lib/datepicker/calendar/calendar.component.ts

When providing a mix or max date value to the datepicker component, the "today" button is now only disabled if today falls before the min date or after the max date.

fix(datepicker): WCASHMERE-53: Datepicker today button fixed

---

projects/cashmere/src/lib/file-input/file-input.component.html

It looks like we might have IE issues unless we include the button type.

fix(file input): fix potential issue with IE

---

projects/cashmere-examples/src/lib/typeahead-fetch/item.ts
projects/cashmere-examples/src/lib/typeahead-fetch/search.service.ts
projects/cashmere-examples/src/lib/typeahead-fetch/typeahead-fetch-example.component.html
projects/cashmere-examples/src/lib/typeahead-fetch/typeahead-fetch-example.component.scss
projects/cashmere-examples/src/lib/typeahead-fetch/typeahead-fetch-example.component.ts
projects/cashmere/src/lib/typeahead/typeahead.component.html
projects/cashmere/src/lib/typeahead/typeahead.component.scss
projects/cashmere/src/lib/typeahead/typeahead.component.ts
projects/cashmere/src/lib/typeahead/typeahead.module.ts
src/app/core/document-items.service.ts

Add debounce to prevent the valueChange event from emitting while user is still typing. Add a
configurable spinner that can be toggled on and off to show that the typeahead is working. Add an example demonstrating new functionality fetching data from remote API.

feat(typeahead): add debounce and configurable spinner

---

projects/cashmere/src/lib/typeahead-title/typeahead-title.component.html
projects/cashmere/src/lib/typeahead-title/typeahead-title.component.scss
projects/cashmere/src/lib/typeahead/typeahead.component.ts

up, down, esc, enter, etc keystrokes were no longer working properly. Typeahead title was causing
an error in the console.
- hide the typeahead in the title component rather than not rendering it all. This ensures that all event handlers get attached properly and that the component does not get updated after the change lifecycle hook has ran which was causing console errors
- fix the handling of keystrokes so that all keys are being detected properly in the typeahead

fix(typeahead/typeahead title): fix keystrokes being ignored and error

---

projects/cashmere-examples/src/lib/date-range-time/date-range-time-example.component.html
projects/cashmere-examples/src/lib/date-range/date-range-example.component.html
projects/cashmere-examples/src/lib/datepicker/datepicker-example.component.html
projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.html
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.scss
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.ts
projects/cashmere/src/lib/datepicker/calendar/calendar-header.html
projects/cashmere/src/lib/datepicker/calendar/calendar.component.scss

The following issues have been fixed:
- throws `ExpressionChangedAfterItHasBeenCheckedError` whenever it is opened/closed
- chevron should animate
- too much padding on left (doesn't line up with other form elements when inline)
- remove `icon-right` class from the examples since it is not doing anything and is getting propagated all over (copy and paste)
- error message overlaps with month label (see screenshot)

feat(daterange): WCASHMERE-164: Fix many issues with daterange

---

projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.scss
src/app/demos/sidenav-demo/sidenav-demo.component.html

fix linewrapping and highlighting of children when the parent is the active router link

fix(sidenav): fix styling on links

---

projects/cashmere/src/lib/typeahead/typeahead-item/typeahead-item.component.html
projects/cashmere/src/lib/typeahead/typeahead.component.ts

This fixes 2 issues that were affecting the typeahead and typeahead title. First, clicking outside
of the typeahead when using it in the title would not cause it to return to the title view instead
the typeahead stayed visible. Second, clikcing on a typeahead item to select would not cause it to
become the selected item because of event firing order.

fix(typeahead): fix the firing order of events

---

projects/cashmere-examples/src/lib/input-phone-number/input-phone-number-example.component.html
projects/cashmere-examples/src/lib/input-phone-number/input-phone-number-example.component.ts
projects/cashmere/src/lib/input/phone-mask.directive.ts

Sorry, the reformatting from 2 spaces to 4 spaces makes it look like a lot more changes than there really are. There is a new example that helps see it work with or without an initial value. I made 3 main changes here though:
1. format the initial value (in ngAfterViewInit)
2. trim the overall length of the number so you can't paste in a 100 digit phone number
3. Remove a dead case ')' from the switch statement

fix(phone input): format initial value

---

projects/cashmere-examples/src/lib/input-currency/input-currency-example.component.html
projects/cashmere-examples/src/lib/input-currency/input-currency-example.component.ts
projects/cashmere/src/lib/input/currency.directive.ts

The currency component will now format initial values passed in to it. The currencyControl input is
no longer valid since it was redundant.
BREAKING CHANGE: The currencyControl is no longer a valid input. The formControl is used for this
purpose.

fix(currency input): fix formatting and simplify api

---

projects/cashmere/src/lib/input/phone-mask.directive.ts

when using the backspace on the input, the first three digits of the phone number can now be deleted
without needing to select with the mouse first

fix(phone directive): WCASHMERE-192: deleting first three digits fixed

---

projects/cashmere-examples/src/lib/table-sort/table-sort-example.component.html
projects/cashmere-examples/src/lib/table-sort/table-sort-example.component.scss
projects/cashmere/src/lib/sass/table.scss
projects/cashmere/src/lib/sass/tables.scss
projects/cashmere/src/lib/table/table.md

Fixed alignment so that right align and left indicator justify correctly when stacked. Also, made it
clear in documentation that when using right align, the left indicator should also be used.

fix(table sort): WCASHMERE-188: Fixed alignment on table headers

---

projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.html

It turns out that all of the trouble we were having with getting the correct sidenav link to be active is a bug in angular. This is the workaround most widely accepted. 
https://github.com/angular/angular/issues/18469#issuecomment-345436335

fix(sidenav): fix the active state of sidenav links

---

projects/cashmere-examples/src/lib/typeahead-overview/typeahead-overview-example.component.html
projects/cashmere/src/lib/typeahead/typeahead.component.ts

Clicking on the typehead even when it was disabled would still cause it to show all of the results.
The disabled state now works correctly.

fix(typeahead): fix issues with disabled state

---

projects/cashmere/src/lib/sass/table.scss

Fixed min-height of table row to 48px and ensured that anything larger still bound by row padding.
Also centered content vertically in rows.

feat(table): WCASHMERE-213: updated table styles

---

projects/cashmere-examples/src/lib/typeahead-title-multiple/typeahead-title-multiple-example.component.html
projects/cashmere-examples/src/lib/typeahead-title-multiple/typeahead-title-multiple-example.component.ts
projects/cashmere-examples/src/lib/typeahead-title-no-alert/typeahead-title-no-alert-example.component.html
projects/cashmere-examples/src/lib/typeahead-title-no-alert/typeahead-title-no-alert-example.component.ts
projects/cashmere/src/lib/typeahead-title/typeahead-title.component.html
projects/cashmere/src/lib/typeahead-title/typeahead-title.component.scss
projects/cashmere/src/lib/typeahead-title/typeahead-title.component.ts
src/app/core/document-items.service.ts

The red border is intended to draw the users attention to the empty component. It is implemented as
an input so that this effect can be disabled if desired.

feat(typeahead title): add red border to empty typeahead title

---

projects/cashmere-examples/src/lib/typeahead-title-multiple/typeahead-title-multiple-example.component.html
projects/cashmere/src/lib/typeahead-title/typeahead-title.component.scss

Fix the typeahead title so that it has a consistent white background. Provide an example that
demonstrates this as well.

fix(typeahead title): fix the typeahead title background color

---

projects/cashmere/src/lib/sass/_colors.scss
projects/cashmere/src/lib/typeahead/typeahead.component.ts

- Expose $blue-darkest in the colors file for external consumption.
- Snuck in a little doc change for typeahead
- Looks like I used a different version of commitizen that worked a bit differently (new computer)

fix(colors): make blue-darkest color available to consume

---

projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.html
projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.scss
projects/cashmere/src/lib/sidenav/sidenav-link/sidenav-link.component.ts
src/app/demos/sidenav-demo/sidenav-demo.component.html

I just made up a feature that wanted. Let me know if you hate it.
- Add the ability to initialize a link to open so that its children will be shown upon initialization.
After initialization, it works completely normal.
- Also, fixed an issue where after clicking to toggle a link (show children) the focus state added a white outline. We don't want that happening.

feat(sidenav): add ability to initialize open

---

projects/cashmere-examples/src/lib/select-borderless/select-borderless-example.component.html
projects/cashmere-examples/src/lib/select-borderless/select-borderless-example.component.scss
projects/cashmere-examples/src/lib/select-borderless/select-borderless-example.component.ts
projects/cashmere-examples/src/lib/select-object/select-object-example.component.ts
projects/cashmere/src/lib/select/select.component.html
projects/cashmere/src/lib/select/select.component.scss
projects/cashmere/src/lib/select/select.component.ts
src/app/core/document-items.service.ts

The borderless option defaults to false so that it continues to work as it has. When set to true,
the select box will still function like a normal select box but it will not have a border around so
that it looks more floating.

feat(select): add a borderless option

---

projects/cashmere-examples/src/lib/datepicker-min-max/datepicker-min-max-example.component.html
projects/cashmere-examples/src/lib/datepicker-min-max/datepicker-min-max-example.component.ts
projects/cashmere/src/lib/datepicker/datepicker-input/datepicker-input.directive.ts

The comparison for validity on the field was still using the old compareDate so if you selected the min or max it had the potential to fail validation (depending on the time of day).

fix(datepicker): fix validator when using min/max date

---

projects/cashmere-examples/src/lib/multi-select-picker-rich-component/multi-select-picker-rich-component-example.component.ts
projects/cashmere-examples/src/lib/multi-select-picker-rich-template/multi-select-picker-rich-template-example.component.html
projects/cashmere-examples/src/lib/multi-select-picker-rich-template/multi-select-picker-rich-template-example.component.scss
projects/cashmere/src/lib/multi-select-picker/multi-select-picker.component.ts

If either the selected values or the unselected values were empty then the component would not offer
any options to select in the dropdown.

fix(multiselectpicker): fix issue if there are no selected or unselected

---

projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.html
projects/cashmere/src/lib/date-range/calendar-wrapper/calendar-wrapper.component.ts
projects/cashmere/src/lib/date-range/date-range.module.ts
projects/cashmere/src/lib/date-range/picker-overlay/picker-overlay.component.html

If a parent form calls markAllAsTouched then the daterange calendar input shows errors and they will
return each time the calendar dialog is opened.

fix(daterange): allow daterange errors to be cleared

---

projects/cashmere-examples/src/lib/progress-bar/progress-bar-example.component.ts
projects/cashmere/src/lib/progress-bar/progress-bar.component.ts

The progress bar now sets the focus to the first item if it finds that no item has focus.

fix(progress bar): wCASHMERE-238: Fixed progress bar focus issue

---

projects/cashmere-examples/src/lib/typeahead-silent-focus/typeahead-silent-focus-example.component.html
projects/cashmere-examples/src/lib/typeahead-silent-focus/typeahead-silent-focus-example.component.scss
projects/cashmere-examples/src/lib/typeahead-silent-focus/typeahead-silent-focus-example.component.ts
projects/cashmere/src/lib/typeahead/typeahead.component.html
projects/cashmere/src/lib/typeahead/typeahead.component.ts
src/app/core/document-items.service.ts

The typeahead component clears the selected item when it receives focus. Added a configuration to
all it to not clear the selected item when tabbed into but it will still clear it and show results
if the value in the input is empty string or if it is clicked. Made the new default to not clear
item.

feat(typeahead): fix tabbing through typeahead component
